<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="8" total="14" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="276047" started-at="2022-04-12T12:02:02Z" finished-at="2022-04-12T12:06:38Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="276047" started-at="2022-04-12T12:02:02Z" finished-at="2022-04-12T12:06:38Z">
      <class name="Organazation.CreateContactwithBaseclassTest">
        <test-method status="PASS" signature="OpenDataBase()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="OpenDataBase" is-config="true" duration-ms="78" started-at="2022-04-12T12:02:01Z" finished-at="2022-04-12T12:02:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenDataBase -->
        <test-method status="PASS" signature="ParallelExecution()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="ParallelExecution" is-config="true" duration-ms="0" started-at="2022-04-12T12:02:02Z" finished-at="2022-04-12T12:02:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ParallelExecution -->
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="LaunchBrowser" is-config="true" duration-ms="79682" started-at="2022-04-12T12:02:02Z" finished-at="2022-04-12T12:03:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="LoginToApplication" is-config="true" duration-ms="51311" started-at="2022-04-12T12:03:22Z" finished-at="2022-04-12T12:04:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="createContact()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="createContact" duration-ms="66717" started-at="2022-04-12T12:04:13Z" finished-at="2022-04-12T12:05:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createContact -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="LogoutFromApplication" is-config="true" duration-ms="5044" started-at="2022-04-12T12:05:20Z" finished-at="2022-04-12T12:05:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="CloseBrowser" is-config="true" duration-ms="4049" started-at="2022-04-12T12:05:25Z" finished-at="2022-04-12T12:05:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
        <test-method status="PASS" signature="CloseparallelExecution()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="CloseparallelExecution" is-config="true" duration-ms="0" started-at="2022-04-12T12:06:38Z" finished-at="2022-04-12T12:06:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseparallelExecution -->
        <test-method status="PASS" signature="CloseDatabaseConnection()[pri:0, instance:Organazation.CreateContactwithBaseclassTest@35fb3008]" name="CloseDatabaseConnection" is-config="true" duration-ms="1" started-at="2022-04-12T12:06:38Z" finished-at="2022-04-12T12:06:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDatabaseConnection -->
      </class> <!-- Organazation.CreateContactwithBaseclassTest -->
      <class name="SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest">
        <test-method status="PASS" signature="LaunchBrowser()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest@54a097cc]" name="LaunchBrowser" is-config="true" duration-ms="16654" started-at="2022-04-12T12:05:29Z" finished-at="2022-04-12T12:05:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchBrowser -->
        <test-method status="PASS" signature="LoginToApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest@54a097cc]" name="LoginToApplication" is-config="true" duration-ms="6373" started-at="2022-04-12T12:05:46Z" finished-at="2022-04-12T12:05:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApplication -->
        <test-method status="PASS" signature="CreateOrgwithType()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest@54a097cc]" name="CreateOrgwithType" duration-ms="39160" started-at="2022-04-12T12:05:52Z" finished-at="2022-04-12T12:06:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateOrgwithType -->
        <test-method status="PASS" signature="LogoutFromApplication()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest@54a097cc]" name="LogoutFromApplication" is-config="true" duration-ms="3281" started-at="2022-04-12T12:06:31Z" finished-at="2022-04-12T12:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApplication -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest@54a097cc]" name="CloseBrowser" is-config="true" duration-ms="1754" started-at="2022-04-12T12:06:35Z" finished-at="2022-04-12T12:06:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- SeleniumFrameworkWithTestNg.CreateOrganizationWithTypeWithBaseclassTest -->
      <class name="Practice.RetryImplyTest">
        <test-method status="SKIP" signature="create()[pri:0, instance:Practice.RetryImplyTest@7225790e]" name="create" duration-ms="2" started-at="2022-04-12T12:06:36Z" finished-at="2022-04-12T12:06:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Practice.RetryImplyTest.create(RetryImplyTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="create()[pri:0, instance:Practice.RetryImplyTest@7225790e]" name="create" duration-ms="1" started-at="2022-04-12T12:06:36Z" finished-at="2022-04-12T12:06:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Practice.RetryImplyTest.create(RetryImplyTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="create()[pri:0, instance:Practice.RetryImplyTest@7225790e]" name="create" duration-ms="1" started-at="2022-04-12T12:06:36Z" finished-at="2022-04-12T12:06:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Practice.RetryImplyTest.create(RetryImplyTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="FAIL" signature="create()[pri:0, instance:Practice.RetryImplyTest@7225790e]" name="create" duration-ms="3" started-at="2022-04-12T12:06:36Z" finished-at="2022-04-12T12:06:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Practice.RetryImplyTest.create(RetryImplyTest.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
      </class> <!-- Practice.RetryImplyTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
